### ISSUE TITLE
[event_details] link attendance button to voting

### ISSUE THREAD

**Issue by Michael-Parekh** [Michael-Parekh/munchmate#22]
"On the event detail page, its not clear what the "Are you at the event?" button does, or that you can event interact with it. Consider you are a user coming with the intent, "I want to review this event." What button(s) are you looking for, what buttons are you likely to try, and in what order?"

**Comment by yhuang0701** [comment]
By discussion - We agreed not to link the attendance with upvoting/downvoting, and I will display it statically.
